name: ba-dua_coverage
on:
  push:
    branches:
      - master
  pull_request:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'
  
      - name: Build
        run: mvn clean verify -P ba-dua-cov
