
on:
  push:
    branches:
    - master

  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version:  8
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install -Dsurefire.rerunFailingTestsCount=2
      - name: Upload surefire report
        uses: actions/upload-artifact@v3
        with:
          name: pit-report
          path: tajo-cluster-tests/target/surefire-reports/
          if-no-files-found: error
      - name: Upload failsafe report
        uses: actions/upload-artifact@v3
        with:
          name: pit-report
          path: tajo-cluster-tests/target/failsafe-reports/
          if-no-files-found: error
